dist: bionic

language: cpp
compiler: gcc

git:
  submodules: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
    
before_script: cd installer
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - bash compile.sh
