# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vincenzo/Github/work_version_beta/SpyCblock

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vincenzo/Github/work_version_beta/SpyCblock

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vincenzo/Github/work_version_beta/SpyCblock/CMakeFiles /home/vincenzo/Github/work_version_beta/SpyCblock/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vincenzo/Github/work_version_beta/SpyCblock/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpyCBlockTests

# Build rule for target.
SpyCBlockTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpyCBlockTests
.PHONY : SpyCBlockTests

# fast build rule for target.
SpyCBlockTests/fast:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/build
.PHONY : SpyCBlockTests/fast

#=============================================================================
# Target rules for targets named SpyCBlock

# Build rule for target.
SpyCBlock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpyCBlock
.PHONY : SpyCBlock

# fast build rule for target.
SpyCBlock/fast:
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/build
.PHONY : SpyCBlock/fast

core/ConfiguratorSingleton.o: core/ConfiguratorSingleton.cpp.o

.PHONY : core/ConfiguratorSingleton.o

# target to build an object file
core/ConfiguratorSingleton.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/core/ConfiguratorSingleton.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/ConfiguratorSingleton.cpp.o
.PHONY : core/ConfiguratorSingleton.cpp.o

core/ConfiguratorSingleton.i: core/ConfiguratorSingleton.cpp.i

.PHONY : core/ConfiguratorSingleton.i

# target to preprocess a source file
core/ConfiguratorSingleton.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/core/ConfiguratorSingleton.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/ConfiguratorSingleton.cpp.i
.PHONY : core/ConfiguratorSingleton.cpp.i

core/ConfiguratorSingleton.s: core/ConfiguratorSingleton.cpp.s

.PHONY : core/ConfiguratorSingleton.s

# target to generate assembly for a file
core/ConfiguratorSingleton.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/core/ConfiguratorSingleton.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/ConfiguratorSingleton.cpp.s
.PHONY : core/ConfiguratorSingleton.cpp.s

core/ParserMain.o: core/ParserMain.cpp.o

.PHONY : core/ParserMain.o

# target to build an object file
core/ParserMain.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/ParserMain.cpp.o
.PHONY : core/ParserMain.cpp.o

core/ParserMain.i: core/ParserMain.cpp.i

.PHONY : core/ParserMain.i

# target to preprocess a source file
core/ParserMain.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/ParserMain.cpp.i
.PHONY : core/ParserMain.cpp.i

core/ParserMain.s: core/ParserMain.cpp.s

.PHONY : core/ParserMain.s

# target to generate assembly for a file
core/ParserMain.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/ParserMain.cpp.s
.PHONY : core/ParserMain.cpp.s

core/SpyCBlock.o: core/SpyCBlock.cpp.o

.PHONY : core/SpyCBlock.o

# target to build an object file
core/SpyCBlock.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/SpyCBlock.cpp.o
.PHONY : core/SpyCBlock.cpp.o

core/SpyCBlock.i: core/SpyCBlock.cpp.i

.PHONY : core/SpyCBlock.i

# target to preprocess a source file
core/SpyCBlock.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/SpyCBlock.cpp.i
.PHONY : core/SpyCBlock.cpp.i

core/SpyCBlock.s: core/SpyCBlock.cpp.s

.PHONY : core/SpyCBlock.s

# target to generate assembly for a file
core/SpyCBlock.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/core/SpyCBlock.cpp.s
.PHONY : core/SpyCBlock.cpp.s

crypto/CryptoCore.o: crypto/CryptoCore.cpp.o

.PHONY : crypto/CryptoCore.o

# target to build an object file
crypto/CryptoCore.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/crypto/CryptoCore.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/crypto/CryptoCore.cpp.o
.PHONY : crypto/CryptoCore.cpp.o

crypto/CryptoCore.i: crypto/CryptoCore.cpp.i

.PHONY : crypto/CryptoCore.i

# target to preprocess a source file
crypto/CryptoCore.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/crypto/CryptoCore.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/crypto/CryptoCore.cpp.i
.PHONY : crypto/CryptoCore.cpp.i

crypto/CryptoCore.s: crypto/CryptoCore.cpp.s

.PHONY : crypto/CryptoCore.s

# target to generate assembly for a file
crypto/CryptoCore.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/crypto/CryptoCore.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/crypto/CryptoCore.cpp.s
.PHONY : crypto/CryptoCore.cpp.s

crypto/UtilCrypto.o: crypto/UtilCrypto.cpp.o

.PHONY : crypto/UtilCrypto.o

# target to build an object file
crypto/UtilCrypto.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/crypto/UtilCrypto.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/crypto/UtilCrypto.cpp.o
.PHONY : crypto/UtilCrypto.cpp.o

crypto/UtilCrypto.i: crypto/UtilCrypto.cpp.i

.PHONY : crypto/UtilCrypto.i

# target to preprocess a source file
crypto/UtilCrypto.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/crypto/UtilCrypto.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/crypto/UtilCrypto.cpp.i
.PHONY : crypto/UtilCrypto.cpp.i

crypto/UtilCrypto.s: crypto/UtilCrypto.cpp.s

.PHONY : crypto/UtilCrypto.s

# target to generate assembly for a file
crypto/UtilCrypto.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/crypto/UtilCrypto.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/crypto/UtilCrypto.cpp.s
.PHONY : crypto/UtilCrypto.cpp.s

cryptobitcoin/Sha256.o: cryptobitcoin/Sha256.cpp.o

.PHONY : cryptobitcoin/Sha256.o

# target to build an object file
cryptobitcoin/Sha256.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Sha256.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Sha256.cpp.o
.PHONY : cryptobitcoin/Sha256.cpp.o

cryptobitcoin/Sha256.i: cryptobitcoin/Sha256.cpp.i

.PHONY : cryptobitcoin/Sha256.i

# target to preprocess a source file
cryptobitcoin/Sha256.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Sha256.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Sha256.cpp.i
.PHONY : cryptobitcoin/Sha256.cpp.i

cryptobitcoin/Sha256.s: cryptobitcoin/Sha256.cpp.s

.PHONY : cryptobitcoin/Sha256.s

# target to generate assembly for a file
cryptobitcoin/Sha256.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Sha256.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Sha256.cpp.s
.PHONY : cryptobitcoin/Sha256.cpp.s

cryptobitcoin/Sha256Hash.o: cryptobitcoin/Sha256Hash.cpp.o

.PHONY : cryptobitcoin/Sha256Hash.o

# target to build an object file
cryptobitcoin/Sha256Hash.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Sha256Hash.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Sha256Hash.cpp.o
.PHONY : cryptobitcoin/Sha256Hash.cpp.o

cryptobitcoin/Sha256Hash.i: cryptobitcoin/Sha256Hash.cpp.i

.PHONY : cryptobitcoin/Sha256Hash.i

# target to preprocess a source file
cryptobitcoin/Sha256Hash.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Sha256Hash.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Sha256Hash.cpp.i
.PHONY : cryptobitcoin/Sha256Hash.cpp.i

cryptobitcoin/Sha256Hash.s: cryptobitcoin/Sha256Hash.cpp.s

.PHONY : cryptobitcoin/Sha256Hash.s

# target to generate assembly for a file
cryptobitcoin/Sha256Hash.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Sha256Hash.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Sha256Hash.cpp.s
.PHONY : cryptobitcoin/Sha256Hash.cpp.s

cryptobitcoin/Utils.o: cryptobitcoin/Utils.cpp.o

.PHONY : cryptobitcoin/Utils.o

# target to build an object file
cryptobitcoin/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Utils.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Utils.cpp.o
.PHONY : cryptobitcoin/Utils.cpp.o

cryptobitcoin/Utils.i: cryptobitcoin/Utils.cpp.i

.PHONY : cryptobitcoin/Utils.i

# target to preprocess a source file
cryptobitcoin/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Utils.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Utils.cpp.i
.PHONY : cryptobitcoin/Utils.cpp.i

cryptobitcoin/Utils.s: cryptobitcoin/Utils.cpp.s

.PHONY : cryptobitcoin/Utils.s

# target to generate assembly for a file
cryptobitcoin/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/cryptobitcoin/Utils.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/cryptobitcoin/Utils.cpp.s
.PHONY : cryptobitcoin/Utils.cpp.s

include/cpp-properties/src/Properties.o: include/cpp-properties/src/Properties.cpp.o

.PHONY : include/cpp-properties/src/Properties.o

# target to build an object file
include/cpp-properties/src/Properties.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/Properties.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/Properties.cpp.o
.PHONY : include/cpp-properties/src/Properties.cpp.o

include/cpp-properties/src/Properties.i: include/cpp-properties/src/Properties.cpp.i

.PHONY : include/cpp-properties/src/Properties.i

# target to preprocess a source file
include/cpp-properties/src/Properties.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/Properties.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/Properties.cpp.i
.PHONY : include/cpp-properties/src/Properties.cpp.i

include/cpp-properties/src/Properties.s: include/cpp-properties/src/Properties.cpp.s

.PHONY : include/cpp-properties/src/Properties.s

# target to generate assembly for a file
include/cpp-properties/src/Properties.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/Properties.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/Properties.cpp.s
.PHONY : include/cpp-properties/src/Properties.cpp.s

include/cpp-properties/src/PropertiesParser.o: include/cpp-properties/src/PropertiesParser.cpp.o

.PHONY : include/cpp-properties/src/PropertiesParser.o

# target to build an object file
include/cpp-properties/src/PropertiesParser.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/PropertiesParser.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/PropertiesParser.cpp.o
.PHONY : include/cpp-properties/src/PropertiesParser.cpp.o

include/cpp-properties/src/PropertiesParser.i: include/cpp-properties/src/PropertiesParser.cpp.i

.PHONY : include/cpp-properties/src/PropertiesParser.i

# target to preprocess a source file
include/cpp-properties/src/PropertiesParser.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/PropertiesParser.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/PropertiesParser.cpp.i
.PHONY : include/cpp-properties/src/PropertiesParser.cpp.i

include/cpp-properties/src/PropertiesParser.s: include/cpp-properties/src/PropertiesParser.cpp.s

.PHONY : include/cpp-properties/src/PropertiesParser.s

# target to generate assembly for a file
include/cpp-properties/src/PropertiesParser.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/PropertiesParser.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/PropertiesParser.cpp.s
.PHONY : include/cpp-properties/src/PropertiesParser.cpp.s

include/cpp-properties/src/PropertiesUtils.o: include/cpp-properties/src/PropertiesUtils.cpp.o

.PHONY : include/cpp-properties/src/PropertiesUtils.o

# target to build an object file
include/cpp-properties/src/PropertiesUtils.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/PropertiesUtils.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/PropertiesUtils.cpp.o
.PHONY : include/cpp-properties/src/PropertiesUtils.cpp.o

include/cpp-properties/src/PropertiesUtils.i: include/cpp-properties/src/PropertiesUtils.cpp.i

.PHONY : include/cpp-properties/src/PropertiesUtils.i

# target to preprocess a source file
include/cpp-properties/src/PropertiesUtils.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/PropertiesUtils.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/PropertiesUtils.cpp.i
.PHONY : include/cpp-properties/src/PropertiesUtils.cpp.i

include/cpp-properties/src/PropertiesUtils.s: include/cpp-properties/src/PropertiesUtils.cpp.s

.PHONY : include/cpp-properties/src/PropertiesUtils.s

# target to generate assembly for a file
include/cpp-properties/src/PropertiesUtils.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/include/cpp-properties/src/PropertiesUtils.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/include/cpp-properties/src/PropertiesUtils.cpp.s
.PHONY : include/cpp-properties/src/PropertiesUtils.cpp.s

persistence/DAOBlockchain.o: persistence/DAOBlockchain.cpp.o

.PHONY : persistence/DAOBlockchain.o

# target to build an object file
persistence/DAOBlockchain.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/DAOBlockchain.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/DAOBlockchain.cpp.o
.PHONY : persistence/DAOBlockchain.cpp.o

persistence/DAOBlockchain.i: persistence/DAOBlockchain.cpp.i

.PHONY : persistence/DAOBlockchain.i

# target to preprocess a source file
persistence/DAOBlockchain.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/DAOBlockchain.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/DAOBlockchain.cpp.i
.PHONY : persistence/DAOBlockchain.cpp.i

persistence/DAOBlockchain.s: persistence/DAOBlockchain.cpp.s

.PHONY : persistence/DAOBlockchain.s

# target to generate assembly for a file
persistence/DAOBlockchain.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/DAOBlockchain.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/DAOBlockchain.cpp.s
.PHONY : persistence/DAOBlockchain.cpp.s

persistence/DAOException.o: persistence/DAOException.cpp.o

.PHONY : persistence/DAOException.o

# target to build an object file
persistence/DAOException.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/DAOException.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/DAOException.cpp.o
.PHONY : persistence/DAOException.cpp.o

persistence/DAOException.i: persistence/DAOException.cpp.i

.PHONY : persistence/DAOException.i

# target to preprocess a source file
persistence/DAOException.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/DAOException.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/DAOException.cpp.i
.PHONY : persistence/DAOException.cpp.i

persistence/DAOException.s: persistence/DAOException.cpp.s

.PHONY : persistence/DAOException.s

# target to generate assembly for a file
persistence/DAOException.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/DAOException.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/DAOException.cpp.s
.PHONY : persistence/DAOException.cpp.s

persistence/SerializationUtil.o: persistence/SerializationUtil.cpp.o

.PHONY : persistence/SerializationUtil.o

# target to build an object file
persistence/SerializationUtil.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/SerializationUtil.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/SerializationUtil.cpp.o
.PHONY : persistence/SerializationUtil.cpp.o

persistence/SerializationUtil.i: persistence/SerializationUtil.cpp.i

.PHONY : persistence/SerializationUtil.i

# target to preprocess a source file
persistence/SerializationUtil.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/SerializationUtil.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/SerializationUtil.cpp.i
.PHONY : persistence/SerializationUtil.cpp.i

persistence/SerializationUtil.s: persistence/SerializationUtil.cpp.s

.PHONY : persistence/SerializationUtil.s

# target to generate assembly for a file
persistence/SerializationUtil.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/SerializationUtil.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/SerializationUtil.cpp.s
.PHONY : persistence/SerializationUtil.cpp.s

persistence/json/DAOBlkToJson.o: persistence/json/DAOBlkToJson.cpp.o

.PHONY : persistence/json/DAOBlkToJson.o

# target to build an object file
persistence/json/DAOBlkToJson.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/json/DAOBlkToJson.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/json/DAOBlkToJson.cpp.o
.PHONY : persistence/json/DAOBlkToJson.cpp.o

persistence/json/DAOBlkToJson.i: persistence/json/DAOBlkToJson.cpp.i

.PHONY : persistence/json/DAOBlkToJson.i

# target to preprocess a source file
persistence/json/DAOBlkToJson.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/json/DAOBlkToJson.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/json/DAOBlkToJson.cpp.i
.PHONY : persistence/json/DAOBlkToJson.cpp.i

persistence/json/DAOBlkToJson.s: persistence/json/DAOBlkToJson.cpp.s

.PHONY : persistence/json/DAOBlkToJson.s

# target to generate assembly for a file
persistence/json/DAOBlkToJson.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/json/DAOBlkToJson.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/json/DAOBlkToJson.cpp.s
.PHONY : persistence/json/DAOBlkToJson.cpp.s

persistence/json/DAOJson.o: persistence/json/DAOJson.cpp.o

.PHONY : persistence/json/DAOJson.o

# target to build an object file
persistence/json/DAOJson.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/json/DAOJson.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/json/DAOJson.cpp.o
.PHONY : persistence/json/DAOJson.cpp.o

persistence/json/DAOJson.i: persistence/json/DAOJson.cpp.i

.PHONY : persistence/json/DAOJson.i

# target to preprocess a source file
persistence/json/DAOJson.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/json/DAOJson.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/json/DAOJson.cpp.i
.PHONY : persistence/json/DAOJson.cpp.i

persistence/json/DAOJson.s: persistence/json/DAOJson.cpp.s

.PHONY : persistence/json/DAOJson.s

# target to generate assembly for a file
persistence/json/DAOJson.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/persistence/json/DAOJson.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/persistence/json/DAOJson.cpp.s
.PHONY : persistence/json/DAOJson.cpp.s

structure/block/block.o: structure/block/block.cpp.o

.PHONY : structure/block/block.o

# target to build an object file
structure/block/block.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/block/block.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/block/block.cpp.o
.PHONY : structure/block/block.cpp.o

structure/block/block.i: structure/block/block.cpp.i

.PHONY : structure/block/block.i

# target to preprocess a source file
structure/block/block.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/block/block.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/block/block.cpp.i
.PHONY : structure/block/block.cpp.i

structure/block/block.s: structure/block/block.cpp.s

.PHONY : structure/block/block.s

# target to generate assembly for a file
structure/block/block.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/block/block.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/block/block.cpp.s
.PHONY : structure/block/block.cpp.s

structure/block/blockHeader.o: structure/block/blockHeader.cpp.o

.PHONY : structure/block/blockHeader.o

# target to build an object file
structure/block/blockHeader.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/block/blockHeader.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/block/blockHeader.cpp.o
.PHONY : structure/block/blockHeader.cpp.o

structure/block/blockHeader.i: structure/block/blockHeader.cpp.i

.PHONY : structure/block/blockHeader.i

# target to preprocess a source file
structure/block/blockHeader.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/block/blockHeader.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/block/blockHeader.cpp.i
.PHONY : structure/block/blockHeader.cpp.i

structure/block/blockHeader.s: structure/block/blockHeader.cpp.s

.PHONY : structure/block/blockHeader.s

# target to generate assembly for a file
structure/block/blockHeader.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/block/blockHeader.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/block/blockHeader.cpp.s
.PHONY : structure/block/blockHeader.cpp.s

structure/script/scriptCode.o: structure/script/scriptCode.cpp.o

.PHONY : structure/script/scriptCode.o

# target to build an object file
structure/script/scriptCode.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/script/scriptCode.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/script/scriptCode.cpp.o
.PHONY : structure/script/scriptCode.cpp.o

structure/script/scriptCode.i: structure/script/scriptCode.cpp.i

.PHONY : structure/script/scriptCode.i

# target to preprocess a source file
structure/script/scriptCode.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/script/scriptCode.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/script/scriptCode.cpp.i
.PHONY : structure/script/scriptCode.cpp.i

structure/script/scriptCode.s: structure/script/scriptCode.cpp.s

.PHONY : structure/script/scriptCode.s

# target to generate assembly for a file
structure/script/scriptCode.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/script/scriptCode.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/script/scriptCode.cpp.s
.PHONY : structure/script/scriptCode.cpp.s

structure/transaction/RawTransaction.o: structure/transaction/RawTransaction.cpp.o

.PHONY : structure/transaction/RawTransaction.o

# target to build an object file
structure/transaction/RawTransaction.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/RawTransaction.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/RawTransaction.cpp.o
.PHONY : structure/transaction/RawTransaction.cpp.o

structure/transaction/RawTransaction.i: structure/transaction/RawTransaction.cpp.i

.PHONY : structure/transaction/RawTransaction.i

# target to preprocess a source file
structure/transaction/RawTransaction.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/RawTransaction.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/RawTransaction.cpp.i
.PHONY : structure/transaction/RawTransaction.cpp.i

structure/transaction/RawTransaction.s: structure/transaction/RawTransaction.cpp.s

.PHONY : structure/transaction/RawTransaction.s

# target to generate assembly for a file
structure/transaction/RawTransaction.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/RawTransaction.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/RawTransaction.cpp.s
.PHONY : structure/transaction/RawTransaction.cpp.s

structure/transaction/TransactionInput.o: structure/transaction/TransactionInput.cpp.o

.PHONY : structure/transaction/TransactionInput.o

# target to build an object file
structure/transaction/TransactionInput.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/TransactionInput.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/TransactionInput.cpp.o
.PHONY : structure/transaction/TransactionInput.cpp.o

structure/transaction/TransactionInput.i: structure/transaction/TransactionInput.cpp.i

.PHONY : structure/transaction/TransactionInput.i

# target to preprocess a source file
structure/transaction/TransactionInput.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/TransactionInput.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/TransactionInput.cpp.i
.PHONY : structure/transaction/TransactionInput.cpp.i

structure/transaction/TransactionInput.s: structure/transaction/TransactionInput.cpp.s

.PHONY : structure/transaction/TransactionInput.s

# target to generate assembly for a file
structure/transaction/TransactionInput.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/TransactionInput.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/TransactionInput.cpp.s
.PHONY : structure/transaction/TransactionInput.cpp.s

structure/transaction/TransactionOutput.o: structure/transaction/TransactionOutput.cpp.o

.PHONY : structure/transaction/TransactionOutput.o

# target to build an object file
structure/transaction/TransactionOutput.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/TransactionOutput.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/TransactionOutput.cpp.o
.PHONY : structure/transaction/TransactionOutput.cpp.o

structure/transaction/TransactionOutput.i: structure/transaction/TransactionOutput.cpp.i

.PHONY : structure/transaction/TransactionOutput.i

# target to preprocess a source file
structure/transaction/TransactionOutput.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/TransactionOutput.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/TransactionOutput.cpp.i
.PHONY : structure/transaction/TransactionOutput.cpp.i

structure/transaction/TransactionOutput.s: structure/transaction/TransactionOutput.cpp.s

.PHONY : structure/transaction/TransactionOutput.s

# target to generate assembly for a file
structure/transaction/TransactionOutput.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/transaction/TransactionOutput.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/transaction/TransactionOutput.cpp.s
.PHONY : structure/transaction/TransactionOutput.cpp.s

structure/type/DScript.o: structure/type/DScript.cpp.o

.PHONY : structure/type/DScript.o

# target to build an object file
structure/type/DScript.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/DScript.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/DScript.cpp.o
.PHONY : structure/type/DScript.cpp.o

structure/type/DScript.i: structure/type/DScript.cpp.i

.PHONY : structure/type/DScript.i

# target to preprocess a source file
structure/type/DScript.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/DScript.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/DScript.cpp.i
.PHONY : structure/type/DScript.cpp.i

structure/type/DScript.s: structure/type/DScript.cpp.s

.PHONY : structure/type/DScript.s

# target to generate assembly for a file
structure/type/DScript.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/DScript.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/DScript.cpp.s
.PHONY : structure/type/DScript.cpp.s

structure/type/DVarInt.o: structure/type/DVarInt.cpp.o

.PHONY : structure/type/DVarInt.o

# target to build an object file
structure/type/DVarInt.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/DVarInt.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/DVarInt.cpp.o
.PHONY : structure/type/DVarInt.cpp.o

structure/type/DVarInt.i: structure/type/DVarInt.cpp.i

.PHONY : structure/type/DVarInt.i

# target to preprocess a source file
structure/type/DVarInt.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/DVarInt.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/DVarInt.cpp.i
.PHONY : structure/type/DVarInt.cpp.i

structure/type/DVarInt.s: structure/type/DVarInt.cpp.s

.PHONY : structure/type/DVarInt.s

# target to generate assembly for a file
structure/type/DVarInt.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/DVarInt.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/DVarInt.cpp.s
.PHONY : structure/type/DVarInt.cpp.s

structure/type/Outpoint.o: structure/type/Outpoint.cpp.o

.PHONY : structure/type/Outpoint.o

# target to build an object file
structure/type/Outpoint.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/Outpoint.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/Outpoint.cpp.o
.PHONY : structure/type/Outpoint.cpp.o

structure/type/Outpoint.i: structure/type/Outpoint.cpp.i

.PHONY : structure/type/Outpoint.i

# target to preprocess a source file
structure/type/Outpoint.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/Outpoint.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/Outpoint.cpp.i
.PHONY : structure/type/Outpoint.cpp.i

structure/type/Outpoint.s: structure/type/Outpoint.cpp.s

.PHONY : structure/type/Outpoint.s

# target to generate assembly for a file
structure/type/Outpoint.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/structure/type/Outpoint.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/structure/type/Outpoint.cpp.s
.PHONY : structure/type/Outpoint.cpp.s

test/ConfiguratorSingletonTest.o: test/ConfiguratorSingletonTest.cpp.o

.PHONY : test/ConfiguratorSingletonTest.o

# target to build an object file
test/ConfiguratorSingletonTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/ConfiguratorSingletonTest.cpp.o
.PHONY : test/ConfiguratorSingletonTest.cpp.o

test/ConfiguratorSingletonTest.i: test/ConfiguratorSingletonTest.cpp.i

.PHONY : test/ConfiguratorSingletonTest.i

# target to preprocess a source file
test/ConfiguratorSingletonTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/ConfiguratorSingletonTest.cpp.i
.PHONY : test/ConfiguratorSingletonTest.cpp.i

test/ConfiguratorSingletonTest.s: test/ConfiguratorSingletonTest.cpp.s

.PHONY : test/ConfiguratorSingletonTest.s

# target to generate assembly for a file
test/ConfiguratorSingletonTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/ConfiguratorSingletonTest.cpp.s
.PHONY : test/ConfiguratorSingletonTest.cpp.s

test/DAOBlkToJsonTest.o: test/DAOBlkToJsonTest.cpp.o

.PHONY : test/DAOBlkToJsonTest.o

# target to build an object file
test/DAOBlkToJsonTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOBlkToJsonTest.cpp.o
.PHONY : test/DAOBlkToJsonTest.cpp.o

test/DAOBlkToJsonTest.i: test/DAOBlkToJsonTest.cpp.i

.PHONY : test/DAOBlkToJsonTest.i

# target to preprocess a source file
test/DAOBlkToJsonTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOBlkToJsonTest.cpp.i
.PHONY : test/DAOBlkToJsonTest.cpp.i

test/DAOBlkToJsonTest.s: test/DAOBlkToJsonTest.cpp.s

.PHONY : test/DAOBlkToJsonTest.s

# target to generate assembly for a file
test/DAOBlkToJsonTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOBlkToJsonTest.cpp.s
.PHONY : test/DAOBlkToJsonTest.cpp.s

test/DAOBlockchainTest.o: test/DAOBlockchainTest.cpp.o

.PHONY : test/DAOBlockchainTest.o

# target to build an object file
test/DAOBlockchainTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOBlockchainTest.cpp.o
.PHONY : test/DAOBlockchainTest.cpp.o

test/DAOBlockchainTest.i: test/DAOBlockchainTest.cpp.i

.PHONY : test/DAOBlockchainTest.i

# target to preprocess a source file
test/DAOBlockchainTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOBlockchainTest.cpp.i
.PHONY : test/DAOBlockchainTest.cpp.i

test/DAOBlockchainTest.s: test/DAOBlockchainTest.cpp.s

.PHONY : test/DAOBlockchainTest.s

# target to generate assembly for a file
test/DAOBlockchainTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOBlockchainTest.cpp.s
.PHONY : test/DAOBlockchainTest.cpp.s

test/DAOJsonTest.o: test/DAOJsonTest.cpp.o

.PHONY : test/DAOJsonTest.o

# target to build an object file
test/DAOJsonTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOJsonTest.cpp.o
.PHONY : test/DAOJsonTest.cpp.o

test/DAOJsonTest.i: test/DAOJsonTest.cpp.i

.PHONY : test/DAOJsonTest.i

# target to preprocess a source file
test/DAOJsonTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOJsonTest.cpp.i
.PHONY : test/DAOJsonTest.cpp.i

test/DAOJsonTest.s: test/DAOJsonTest.cpp.s

.PHONY : test/DAOJsonTest.s

# target to generate assembly for a file
test/DAOJsonTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/DAOJsonTest.cpp.s
.PHONY : test/DAOJsonTest.cpp.s

test/ExceptionCompactsizeTest.o: test/ExceptionCompactsizeTest.cpp.o

.PHONY : test/ExceptionCompactsizeTest.o

# target to build an object file
test/ExceptionCompactsizeTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/ExceptionCompactsizeTest.cpp.o
.PHONY : test/ExceptionCompactsizeTest.cpp.o

test/ExceptionCompactsizeTest.i: test/ExceptionCompactsizeTest.cpp.i

.PHONY : test/ExceptionCompactsizeTest.i

# target to preprocess a source file
test/ExceptionCompactsizeTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/ExceptionCompactsizeTest.cpp.i
.PHONY : test/ExceptionCompactsizeTest.cpp.i

test/ExceptionCompactsizeTest.s: test/ExceptionCompactsizeTest.cpp.s

.PHONY : test/ExceptionCompactsizeTest.s

# target to generate assembly for a file
test/ExceptionCompactsizeTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/ExceptionCompactsizeTest.cpp.s
.PHONY : test/ExceptionCompactsizeTest.cpp.s

test/JsonSerializationTest.o: test/JsonSerializationTest.cpp.o

.PHONY : test/JsonSerializationTest.o

# target to build an object file
test/JsonSerializationTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/JsonSerializationTest.cpp.o
.PHONY : test/JsonSerializationTest.cpp.o

test/JsonSerializationTest.i: test/JsonSerializationTest.cpp.i

.PHONY : test/JsonSerializationTest.i

# target to preprocess a source file
test/JsonSerializationTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/JsonSerializationTest.cpp.i
.PHONY : test/JsonSerializationTest.cpp.i

test/JsonSerializationTest.s: test/JsonSerializationTest.cpp.s

.PHONY : test/JsonSerializationTest.s

# target to generate assembly for a file
test/JsonSerializationTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/JsonSerializationTest.cpp.s
.PHONY : test/JsonSerializationTest.cpp.s

test/NullDataTransactionsTest.o: test/NullDataTransactionsTest.cpp.o

.PHONY : test/NullDataTransactionsTest.o

# target to build an object file
test/NullDataTransactionsTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/NullDataTransactionsTest.cpp.o
.PHONY : test/NullDataTransactionsTest.cpp.o

test/NullDataTransactionsTest.i: test/NullDataTransactionsTest.cpp.i

.PHONY : test/NullDataTransactionsTest.i

# target to preprocess a source file
test/NullDataTransactionsTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/NullDataTransactionsTest.cpp.i
.PHONY : test/NullDataTransactionsTest.cpp.i

test/NullDataTransactionsTest.s: test/NullDataTransactionsTest.cpp.s

.PHONY : test/NullDataTransactionsTest.s

# target to generate assembly for a file
test/NullDataTransactionsTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/NullDataTransactionsTest.cpp.s
.PHONY : test/NullDataTransactionsTest.cpp.s

test/SHABitcoinCoreTest.o: test/SHABitcoinCoreTest.cpp.o

.PHONY : test/SHABitcoinCoreTest.o

# target to build an object file
test/SHABitcoinCoreTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/SHABitcoinCoreTest.cpp.o
.PHONY : test/SHABitcoinCoreTest.cpp.o

test/SHABitcoinCoreTest.i: test/SHABitcoinCoreTest.cpp.i

.PHONY : test/SHABitcoinCoreTest.i

# target to preprocess a source file
test/SHABitcoinCoreTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/SHABitcoinCoreTest.cpp.i
.PHONY : test/SHABitcoinCoreTest.cpp.i

test/SHABitcoinCoreTest.s: test/SHABitcoinCoreTest.cpp.s

.PHONY : test/SHABitcoinCoreTest.s

# target to generate assembly for a file
test/SHABitcoinCoreTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/SHABitcoinCoreTest.cpp.s
.PHONY : test/SHABitcoinCoreTest.cpp.s

test/SerealizationTest.o: test/SerealizationTest.cpp.o

.PHONY : test/SerealizationTest.o

# target to build an object file
test/SerealizationTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/SerealizationTest.cpp.o
.PHONY : test/SerealizationTest.cpp.o

test/SerealizationTest.i: test/SerealizationTest.cpp.i

.PHONY : test/SerealizationTest.i

# target to preprocess a source file
test/SerealizationTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/SerealizationTest.cpp.i
.PHONY : test/SerealizationTest.cpp.i

test/SerealizationTest.s: test/SerealizationTest.cpp.s

.PHONY : test/SerealizationTest.s

# target to generate assembly for a file
test/SerealizationTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/SerealizationTest.cpp.s
.PHONY : test/SerealizationTest.cpp.s

test/StructureBitcoinCoreTest.o: test/StructureBitcoinCoreTest.cpp.o

.PHONY : test/StructureBitcoinCoreTest.o

# target to build an object file
test/StructureBitcoinCoreTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/StructureBitcoinCoreTest.cpp.o
.PHONY : test/StructureBitcoinCoreTest.cpp.o

test/StructureBitcoinCoreTest.i: test/StructureBitcoinCoreTest.cpp.i

.PHONY : test/StructureBitcoinCoreTest.i

# target to preprocess a source file
test/StructureBitcoinCoreTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/StructureBitcoinCoreTest.cpp.i
.PHONY : test/StructureBitcoinCoreTest.cpp.i

test/StructureBitcoinCoreTest.s: test/StructureBitcoinCoreTest.cpp.s

.PHONY : test/StructureBitcoinCoreTest.s

# target to generate assembly for a file
test/StructureBitcoinCoreTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/test/StructureBitcoinCoreTest.cpp.s
.PHONY : test/StructureBitcoinCoreTest.cpp.s

util/prevector.o: util/prevector.cpp.o

.PHONY : util/prevector.o

# target to build an object file
util/prevector.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/prevector.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/prevector.cpp.o
.PHONY : util/prevector.cpp.o

util/prevector.i: util/prevector.cpp.i

.PHONY : util/prevector.i

# target to preprocess a source file
util/prevector.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/prevector.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/prevector.cpp.i
.PHONY : util/prevector.cpp.i

util/prevector.s: util/prevector.cpp.s

.PHONY : util/prevector.s

# target to generate assembly for a file
util/prevector.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/prevector.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/prevector.cpp.s
.PHONY : util/prevector.cpp.s

util/strencodings.o: util/strencodings.cpp.o

.PHONY : util/strencodings.o

# target to build an object file
util/strencodings.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/strencodings.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/strencodings.cpp.o
.PHONY : util/strencodings.cpp.o

util/strencodings.i: util/strencodings.cpp.i

.PHONY : util/strencodings.i

# target to preprocess a source file
util/strencodings.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/strencodings.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/strencodings.cpp.i
.PHONY : util/strencodings.cpp.i

util/strencodings.s: util/strencodings.cpp.s

.PHONY : util/strencodings.s

# target to generate assembly for a file
util/strencodings.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/strencodings.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/strencodings.cpp.s
.PHONY : util/strencodings.cpp.s

util/uint256.o: util/uint256.cpp.o

.PHONY : util/uint256.o

# target to build an object file
util/uint256.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/uint256.cpp.o
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/uint256.cpp.o
.PHONY : util/uint256.cpp.o

util/uint256.i: util/uint256.cpp.i

.PHONY : util/uint256.i

# target to preprocess a source file
util/uint256.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/uint256.cpp.i
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/uint256.cpp.i
.PHONY : util/uint256.cpp.i

util/uint256.s: util/uint256.cpp.s

.PHONY : util/uint256.s

# target to generate assembly for a file
util/uint256.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockTests.dir/build.make CMakeFiles/SpyCBlockTests.dir/util/uint256.cpp.s
	$(MAKE) -f CMakeFiles/SpyCBlock.dir/build.make CMakeFiles/SpyCBlock.dir/util/uint256.cpp.s
.PHONY : util/uint256.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SpyCBlockTests"
	@echo "... test"
	@echo "... SpyCBlock"
	@echo "... core/ConfiguratorSingleton.o"
	@echo "... core/ConfiguratorSingleton.i"
	@echo "... core/ConfiguratorSingleton.s"
	@echo "... core/ParserMain.o"
	@echo "... core/ParserMain.i"
	@echo "... core/ParserMain.s"
	@echo "... core/SpyCBlock.o"
	@echo "... core/SpyCBlock.i"
	@echo "... core/SpyCBlock.s"
	@echo "... crypto/CryptoCore.o"
	@echo "... crypto/CryptoCore.i"
	@echo "... crypto/CryptoCore.s"
	@echo "... crypto/UtilCrypto.o"
	@echo "... crypto/UtilCrypto.i"
	@echo "... crypto/UtilCrypto.s"
	@echo "... cryptobitcoin/Sha256.o"
	@echo "... cryptobitcoin/Sha256.i"
	@echo "... cryptobitcoin/Sha256.s"
	@echo "... cryptobitcoin/Sha256Hash.o"
	@echo "... cryptobitcoin/Sha256Hash.i"
	@echo "... cryptobitcoin/Sha256Hash.s"
	@echo "... cryptobitcoin/Utils.o"
	@echo "... cryptobitcoin/Utils.i"
	@echo "... cryptobitcoin/Utils.s"
	@echo "... include/cpp-properties/src/Properties.o"
	@echo "... include/cpp-properties/src/Properties.i"
	@echo "... include/cpp-properties/src/Properties.s"
	@echo "... include/cpp-properties/src/PropertiesParser.o"
	@echo "... include/cpp-properties/src/PropertiesParser.i"
	@echo "... include/cpp-properties/src/PropertiesParser.s"
	@echo "... include/cpp-properties/src/PropertiesUtils.o"
	@echo "... include/cpp-properties/src/PropertiesUtils.i"
	@echo "... include/cpp-properties/src/PropertiesUtils.s"
	@echo "... persistence/DAOBlockchain.o"
	@echo "... persistence/DAOBlockchain.i"
	@echo "... persistence/DAOBlockchain.s"
	@echo "... persistence/DAOException.o"
	@echo "... persistence/DAOException.i"
	@echo "... persistence/DAOException.s"
	@echo "... persistence/SerializationUtil.o"
	@echo "... persistence/SerializationUtil.i"
	@echo "... persistence/SerializationUtil.s"
	@echo "... persistence/json/DAOBlkToJson.o"
	@echo "... persistence/json/DAOBlkToJson.i"
	@echo "... persistence/json/DAOBlkToJson.s"
	@echo "... persistence/json/DAOJson.o"
	@echo "... persistence/json/DAOJson.i"
	@echo "... persistence/json/DAOJson.s"
	@echo "... structure/block/block.o"
	@echo "... structure/block/block.i"
	@echo "... structure/block/block.s"
	@echo "... structure/block/blockHeader.o"
	@echo "... structure/block/blockHeader.i"
	@echo "... structure/block/blockHeader.s"
	@echo "... structure/script/scriptCode.o"
	@echo "... structure/script/scriptCode.i"
	@echo "... structure/script/scriptCode.s"
	@echo "... structure/transaction/RawTransaction.o"
	@echo "... structure/transaction/RawTransaction.i"
	@echo "... structure/transaction/RawTransaction.s"
	@echo "... structure/transaction/TransactionInput.o"
	@echo "... structure/transaction/TransactionInput.i"
	@echo "... structure/transaction/TransactionInput.s"
	@echo "... structure/transaction/TransactionOutput.o"
	@echo "... structure/transaction/TransactionOutput.i"
	@echo "... structure/transaction/TransactionOutput.s"
	@echo "... structure/type/DScript.o"
	@echo "... structure/type/DScript.i"
	@echo "... structure/type/DScript.s"
	@echo "... structure/type/DVarInt.o"
	@echo "... structure/type/DVarInt.i"
	@echo "... structure/type/DVarInt.s"
	@echo "... structure/type/Outpoint.o"
	@echo "... structure/type/Outpoint.i"
	@echo "... structure/type/Outpoint.s"
	@echo "... test/ConfiguratorSingletonTest.o"
	@echo "... test/ConfiguratorSingletonTest.i"
	@echo "... test/ConfiguratorSingletonTest.s"
	@echo "... test/DAOBlkToJsonTest.o"
	@echo "... test/DAOBlkToJsonTest.i"
	@echo "... test/DAOBlkToJsonTest.s"
	@echo "... test/DAOBlockchainTest.o"
	@echo "... test/DAOBlockchainTest.i"
	@echo "... test/DAOBlockchainTest.s"
	@echo "... test/DAOJsonTest.o"
	@echo "... test/DAOJsonTest.i"
	@echo "... test/DAOJsonTest.s"
	@echo "... test/ExceptionCompactsizeTest.o"
	@echo "... test/ExceptionCompactsizeTest.i"
	@echo "... test/ExceptionCompactsizeTest.s"
	@echo "... test/JsonSerializationTest.o"
	@echo "... test/JsonSerializationTest.i"
	@echo "... test/JsonSerializationTest.s"
	@echo "... test/NullDataTransactionsTest.o"
	@echo "... test/NullDataTransactionsTest.i"
	@echo "... test/NullDataTransactionsTest.s"
	@echo "... test/SHABitcoinCoreTest.o"
	@echo "... test/SHABitcoinCoreTest.i"
	@echo "... test/SHABitcoinCoreTest.s"
	@echo "... test/SerealizationTest.o"
	@echo "... test/SerealizationTest.i"
	@echo "... test/SerealizationTest.s"
	@echo "... test/StructureBitcoinCoreTest.o"
	@echo "... test/StructureBitcoinCoreTest.i"
	@echo "... test/StructureBitcoinCoreTest.s"
	@echo "... util/prevector.o"
	@echo "... util/prevector.i"
	@echo "... util/prevector.s"
	@echo "... util/strencodings.o"
	@echo "... util/strencodings.i"
	@echo "... util/strencodings.s"
	@echo "... util/uint256.o"
	@echo "... util/uint256.i"
	@echo "... util/uint256.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

